# Generated by Django 2.2.6 on 2019-10-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_projects_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
