# Generated by Django 2.2.6 on 2019-10-27 04:06

import annotation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_auto_20191027_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=annotation.models.user_directory_path),
        ),
    ]
