# Generated by Django 2.2.6 on 2019-10-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_auto_20191027_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.Profile'),
        ),
    ]
