# Generated by Django 2.2.6 on 2019-10-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_auto_20191027_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotation.Profile'),
            preserve_default=False,
        ),
    ]
