# Generated by Django 2.2.6 on 2019-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_auto_20191027_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
