# Generated by Django 2.2.6 on 2019-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0014_annotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='istagged',
            field=models.BooleanField(default=False),
        ),
    ]
